<h2 align="center">Problem Statement <br><br> Finding out per captia income of Canadian citizen in 2021</h2>

# Part A: Data Preprocessing

## Step 1 : Import Libraries

In [1]:
import numpy as np
import pandas as pd

**numpy: linear algebra (vectos and matrices)  
pandas: open source data for analysis and manipulation tool**

## Step 2: Import data set

In [2]:
dataset=pd.read_csv("captia_income.csv")
dataset

year  per capita income (US$)
0   1970              3399.299037
1   1971              3768.297935
2   1972              4251.175484
3   1973              4804.463248
4   1974              5576.514583
5   1975              5998.144346
6   1976              7062.131392
7   1977              7100.126170
8   1978              7247.967035
9   1979              7602.912681
10  1980              8355.968120
11  1981              9434.390652
12  1982              9619.438377
13  1983             10416.536590
14  1984             10790.328720
15  1985             11018.955850
16  1986             11482.891530
17  1987             12974.806620
18  1988             15080.283450
19  1989             16426.725480
20  1990             16838.673200
21  1991             17266.097690
22  1992             16412.083090
23  1993             15875.586730
24  1994             15755.820270
25  1995             16369.317250
26  1996             16699.826680
27  1997             17310.757750
28  1998             16622.671870
29  1999             17581.024140
30  2000             18987.382410
31  2001             18601.397240
32  2002             19232.175560
33  2003             22739.426280
34  2004             25719.147150
35  2005             29198.055690
36  2006             32738.262900
37  2007             36144.481220
38  2008             37446.486090
39  2009             32755.176820
40  2010             38420.522890
41  2011             42334.711210
42  2012             42665.255970
43  2013             42676.468370
44  2014             41039.893600
45  2015             35175.188980
46  2016             34229.193630

## Step 3: To create Feature Matrix(X) and Dependent Variable Vector(Y)

In [3]:
# [row_start : row_end , column_start : column_end]
# leave blank if you want all values
X=dataset.iloc[:,:-1].values#all rows, all except last column
Y=dataset.iloc[:,-1].values#all rows, only last column

## Step 4: Replacing missing data(Not required)

## Step 5: Encoding(Not required)

## Step 6: Splitting to data set into training data set and testing dataset

In [4]:
from sklearn.model_selection import train_test_split
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.2,random_state=1)
# splits data set into train and test data in an 80:20 ratio

In [5]:
Xtrain

array([[1989],
       [2006],
       [2016],
       [2003],
       [1993],
       [2004],
       [1997],
       [1991],
       [1983],
       [2008],
       [1987],
       [2012],
       [1974],
       [1998],
       [1984],
       [1980],
       [2011],
       [2000],
       [2001],
       [2010],
       [1990],
       [1988],
       [1995],
       [1976],
       [1977],
       [2014],
       [1971],
       [1986],
       [1970],
       [1985],
       [1975],
       [1981],
       [1979],
       [1978],
       [1982],
       [2013],
       [2007]], dtype=int64)

In [6]:
Xtest

array([[1994],
       [1992],
       [2009],
       [2005],
       [1972],
       [1973],
       [1999],
       [2002],
       [2015],
       [1996]], dtype=int64)

In [7]:
Ytrain

array([16426.72548 , 32738.2629  , 34229.19363 , 22739.42628 ,
       15875.58673 , 25719.14715 , 17310.75775 , 17266.09769 ,
       10416.53659 , 37446.48609 , 12974.80662 , 42665.25597 ,
        5576.514583, 16622.67187 , 10790.32872 ,  8355.96812 ,
       42334.71121 , 18987.38241 , 18601.39724 , 38420.52289 ,
       16838.6732  , 15080.28345 , 16369.31725 ,  7062.131392,
        7100.12617 , 41039.8936  ,  3768.297935, 11482.89153 ,
        3399.299037, 11018.95585 ,  5998.144346,  9434.390652,
        7602.912681,  7247.967035,  9619.438377, 42676.46837 ,
       36144.48122 ])

## Step 7: Feature scaling(not required)
**It is a good idea to Feature Scale if the range of data is very large. However, in regression, the range of the data is taken care of by itself, so we may or may not use feature scaling.**

# Part B: Building Linear Model

## Step 1: Training the linear model

In [8]:
from sklearn.linear_model import LinearRegression
LR=LinearRegression()
LR.fit(Xtrain,Ytrain)

LinearRegression()

## Step 2: Testing the linear model

In [9]:
Yestimated=LR.predict(Xtest)

In [10]:
Yestimated

array([20349.94572643, 18613.49135581, 33373.35350612, 29900.44476487,
        1248.94764955,  2117.17483487, 24691.081653  , 27295.76320894,
       38582.716618  , 22086.40009706])

In [11]:
Ytest

array([15755.82027 , 16412.08309 , 32755.17682 , 29198.05569 ,
        4251.175484,  4804.463248, 17581.02414 , 19232.17556 ,
       35175.18898 , 16699.82668 ])

In [12]:
np.concatenate((Yestimated.reshape(len(Yestimated),1),Ytest.reshape(len(Ytest),1)),1)

array([[20349.94572643, 15755.82027   ],
       [18613.49135581, 16412.08309   ],
       [33373.35350612, 32755.17682   ],
       [29900.44476487, 29198.05569   ],
       [ 1248.94764955,  4251.175484  ],
       [ 2117.17483487,  4804.463248  ],
       [24691.081653  , 17581.02414   ],
       [27295.76320894, 19232.17556   ],
       [38582.716618  , 35175.18898   ],
       [22086.40009706, 16699.82668   ]])

# Answering the question

In [13]:
LR.predict([[2021]])

array([43792.07972988])